[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Packages.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.openssl",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.curl",
    "nodejs_20",
    "python3"
]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[phases.install]
cmds = [
    "php artisan storage:link",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"